# theme: jekyll-theme-hacker


# title: Energy-Based and Neurosymbolic Methods for Advanced Cryptanalysis
# description: Cipher classification and side-channel analysis with deep learning

# markdown: kramdown

site_title: Energy-Based and Neurosymbolic Methods for Advanced Cryptanalysis

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

search_enabled: false
heading_anchors: false
