# theme: jekyll-theme-hacker


# title: Energy-Based and Neurosymbolic Methods for Advanced Cryptanalysis
# description: Cipher classification and side-channel analysis with deep learning

# markdown: kramdown
title: " "
site_title: Energy-Based and Neurosymbolic Methods for Advanced Cryptanalysis

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

search_enabled: false
heading_anchors: false

# GitHub icon (top right)
gh_view_link: true
gh_repository: AnuushkaY/EnergyBased-and-Neurosymbolic-Methods-for-Advanced-CrypytAnalysis

# This will appear as a BOX button
aux_links:
  "PROJECT REPOSITORY":
   - "https://github.com/AnuushkaY/EnergyBased-and-Neurosymbolic-Methods-for-Advanced-CrypytAnalysis"

aux_links_new_tab: true
