title: Energy-Based Cryptanalysis
description: Cipher Classification and Side-Channel Analysis with Deep Learning

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

search_enabled: false

nav:
  - Home: index.md
  - Methodology: methodology.md
  - Side-Channel Analysis: sca.md
  - Results: results.md
  - Conclusion: conclusion.md

plugins:
  - jekyll-remote-theme
